name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:24

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Format check
      run: rebar3 fmt --check
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Run tests
      run: rebar3 do eunit, ct
